import struct

PACKET_TYPE_DATA = 0x01
PACKET_TYPE_ACK = 0x02
PACKET_TYPE_TIMESYNC = 0x03

DATA_HEADER_FORMAT = "<BHBBBB"
DATA_HEADER_SIZE = struct.calcsize(DATA_HEADER_FORMAT)

ACK_FLAG_ACCEPTED   = 1 << 0
ACK_FLAG_DUPLICATE  = 1 << 1
ACK_FLAG_CRC_ERROR  = 1 << 2
ACK_FLAG_BUSY       = 1 << 3
